#
# Autogenerated by Thrift Compiler (0.11.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TFrozenDict, TException, TApplicationException
from thrift.protocol.TProtocol import TProtocolException
from thrift.TRecursive import fix_spec

import sys
from .ttypes import *
URI_HOST = "tecs-host-placeholder"
TECS_TCP_SCHEME = "tecs"
TECS_TCP_SECURE_SCHEME = "tecss"
TECS_UDP_SCHEME = "tecs-udp"
SCHEME_RPC = "tecs-rpc"
SCHEME_RPC_HTTP = "tecs-rpc-http"
DEFAULT_CONTEXT = ""
MULTICAST_IPV4 = "224.0.0.1"
MULTICAST_IPV6 = "FF18:0:0:0:224:0:0:1"
DEFAULT_PORT = 9000
HTTP_UPGRADE_HEADER = "TECS/3.0"
TECS_VERSION = Version(**{
    "major": 3,
    "minor": 0,
    "patch": 0,
})
PS_RESOURCE = "/ps"
SERVICE_TYPE_TECS_SERVER = "TECS-SERVER"
